### PR TITLE
Feature/pokete/kartmen

### PR DESCRIPTION
**Pull request by ondrejmyska**

### CODE REVIEW

**Comment by lxgr-linux** [comment]
Hey,
that looks pretty nice, but I would propose making it an evolution of karpi.

**Comment by ondrejmyska** [comment]
> Hey, that looks pretty nice, but I would propose making it an evolution of karpi.

Good idea, it sounds good. I've changed pokete's attributes, feedback is appreciated.

**Comment by lxgr-linux** [comment]
I would rather go with making karpi evolve at a higher level like 30 to make the evolution a way bigger reward, since karpi itself is so shit.

**Comment by ondrejmyska** [comment]
> I would rather go with making karpi evolve at a higher level like 30 to make the evolution a way bigger reward, since karpi itself is so shit.

ok, I've change it

**Review by lxgr-linux — APPROVED** [review]

**Pull request merged**
