### PR TITLE
Add default settings

### PR DESCRIPTION
**Pull request by Tyson453**
Creates default settings to fix an error message that appears whenever a different file tries to access a certain setting that has not yet been set.

### CODE REVIEW

**Comment by magnus-ISU** [comment]
I would do it like this:

```
self.keywords = ["autosave", "animations", "save_trainers", "load_mods"]
self.settings = [Setting(keyword, False) for keyword in self.keywords]
```
Just two lines and if keywords ever gets changed, it should still work.

Also, is there any reason `self.settings` is not a dict itself? From a cursory glance, it seems that making it a dict or even a [DefaultDict](https://www.geeksforgeeks.org/defaultdict-in-python/) could be better than an array trying to pretend to be a dict, and simplify some of the other functions. I believe if this is merged in the current state, each setting will be in there twice, and it might always return False or something.

Also, is the default supposed to be True for all settings? That's what it looks like to me on line 59 of the file.

**Comment by lxgr-linux** [comment]
> Creates default settings to fix an error message that appears whenever a different file tries to access a certain setting that has not yet been set.

What error message are you talking about?

**Comment by magnus-ISU** [comment]
It's a crash related to some line `settings.get("audio").do_something()`

There was an issue with it recently, (I think #190 )? and I also had the crash a bit ago, so something needs to be done.

**Comment by Tyson453** [comment]
Here's the error message:
`Traceback (most recent call last):
  File "C:\Users\tyson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\tyson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tyson\OneDrive\Documents\GitHub\pokete\pokete_classes\audio.py", line 16, in audio_fn
    while settings("audio").val:
  File "C:\Users\tyson\OneDrive\Documents\GitHub\pokete\pokete_classes\settings.py", line 68, in __call__
    return [i for i in self.settings if i.name == name][0]
IndexError: list index out of range`

In the __call__ function for the Settings class it returns `[i for i in self.settings if i.name == name][0]` but if there are no settings in self.settings it will cause the error.

**Comment by lxgr-linux** [comment]
There actually are default settings: [pokete.py#L785](pokete.py#L785)

**Comment by Tyson453** [comment]
> I would do it like this:
> 
> ```
> self.keywords = ["autosave", "animations", "save_trainers", "load_mods"]
> self.settings = [Setting(keyword, False) for keyword in self.keywords]
> ```
> 
I did it like that because I wasn't sure if all of the settings were the same so if 2 of them are default True and the rest are default False, it would make it easier to change.

**Comment by magnus-ISU** [comment]
Like I said on #176, I think this is a concurrency problem. The easiest solution to me would seem to be to use a `DefaultDict`, as those cannot return nothing.

They can't fix what you just said, though it's still less code overall to write
```
self.settings = DefaultDict(...)
self.settings["MyNewSuperCoolSetting"] = "MySuperAwesomeAndQuirkyDefaultValue"
```

**Comment by magnus-ISU** [comment]
Actually there's no concurrent code till later. Weird.

**Comment by lxgr-linux** [comment]
I really really wonder why this does not happen to me.
And the process that plays the music is started way after the settings are set, and `settings.from_dict` makes sure that all settings are initialized.

It would be good to know how `settings.settings` looks loke before the crash.

**Comment by Tyson453** [comment]
I went back to the original code and printed `settings.settings` right before the line that caused the error and all it printed was an empty array.

**Comment by lxgr-linux** [comment]
What python version are you on, maybe the behaviour of multiprocessing changed in python3.10?

**Comment by Tyson453** [comment]
I'm using Python 3.10.0

**Comment by lxgr-linux** [comment]
It would be good to know what the value of settings.settings is, just before the process is started, so in line 29 of audio.py

**Comment by lxgr-linux** [comment]
Please try #203, it may help.

**Comment by Tyson453** [comment]
I did some digging and found that `settings.settings` isn't empty in the first line of `_game()` but once the function gets to `if audio.curr is None: audio.start(_map.song)` inside the `audio.start()` function, when I print settings it outputs an empty array.

What I think is happening is that `pokete.py` is setting a different variable to `settings.settings` then modifying the new variable which means that `settings.settings` is still an empty array so when `audio.start()` tries to access it, it is still an empty array.

**Comment by lxgr-linux** [comment]
> I did some digging and found that `settings.settings` isn't empty in the first line of `_game()` but once the function gets to `if audio.curr is None: audio.start(_map.song)` inside the `audio.start()` function, when I print settings it outputs an empty array.
> 
> What I think is happening is that `pokete.py` is setting a different variable to `settings.settings` then modifying the new variable which means that `settings.settings` is still an empty array so when `audio.start()` tries to access it, it is still an empty array.

Therefore try #203, where the settings is passed by argument to the thread.

**Comment by lxgr-linux** [comment]
closing in favor of #203

**Pull request closed without merging**
