### PR TITLE
Fixed issue with moves

### PR DESCRIPTION
**Pull request by lxgr-linux**
Fixed the game crashing by leveling up after a fight.

### CODE REVIEW

**Comment by lxgr-linux** [comment]
Please verify @magnus-ISU

**Comment by jlultimate** [comment]
AttributeError: 'Figure' object has no attribute 'moves'

still doesn't work, I'm forking the project

**Comment by lxgr-linux** [comment]
In what line does this accure? Are you sure it's the same error?

**Comment by jlultimate** [comment]
Sometimes when I finish fighting a wild Pokete this happens. The last time this happened is when I leveled up my Steini against a Horny, where my Steini levels up to level eight. The Python AttributeError accrued at the end of the error logs, and the keys I type playing the game are typed into the command prompt above, which makes my terminal give me errors. I never had this issue yesterday, when I first installed Pokete on Windows 11.

**Comment by jlultimate** [comment]
https://user-images.githubusercontent.com/89277598/174457502-e20a582d-a45d-4535-b0d3-397dba8b3edc.mp4

**Comment by jlultimate** [comment]
I've been playing around for a while, and it seems that it works in Nice Town Cave, but not in Nice Town.

**Comment by jlultimate** [comment]
hope this helps!

**Comment by jlultimate** [comment]
Oh sorry I'm not that good with Git and Github, thanks I will reinstall

**Pull request merged**
